ALTER TABLE pgb_session.history
    ALTER COLUMN n TYPE BIGINT;

-- Add the global identity only when the column does not already have one, so
-- this script remains valid when run in sequence with later migrations. (The
-- per-session conversion in 65_session_per_session_n.sql removes it again.)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'pgb_session.history'::regclass
          AND attname = 'n'
          AND attidentity <> ''
    ) THEN
        ALTER TABLE pgb_session.history
            ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Advance the identity sequence past the largest existing value. COALESCE/`is_called`
-- keep this valid when the table is empty (the sequence cannot be set below 1).
SELECT setval(
    pg_get_serial_sequence('pgb_session.history', 'n'),
    COALESCE(max(n), 1),
    count(*) > 0
)
FROM pgb_session.history;

\ir 60_pgb_session_open.sql

\ir 60_pgb_session_reload.sql
