ALTER TABLE pgb_session.snapshot
    ADD COLUMN n BIGINT;

WITH numbered AS (
    SELECT ctid, row_number() OVER (ORDER BY ts, session_id, ctid) AS rn
    FROM pgb_session.snapshot
)
UPDATE pgb_session.snapshot s
SET n = numbered.rn
FROM numbered
WHERE s.ctid = numbered.ctid;

ALTER TABLE pgb_session.snapshot
    ALTER COLUMN n SET NOT NULL;

ALTER TABLE pgb_session.snapshot
    ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('pgb_session.snapshot', 'n'),
    COALESCE((
        SELECT n
        FROM pgb_session.snapshot
        ORDER BY n DESC
        LIMIT 1
    ), 0),
    true
);

ALTER TABLE pgb_session.snapshot
    DROP CONSTRAINT IF EXISTS snapshot_pkey;

ALTER TABLE pgb_session.snapshot
    ADD PRIMARY KEY(session_id, n);

\ir 60_pgb_session_open.sql

\ir 60_pgb_session_reload.sql
