ALTER TABLE pgb_session.snapshot
    ADD COLUMN IF NOT EXISTS n BIGINT;

WITH numbered AS (
    SELECT ctid, row_number() OVER (ORDER BY ts, session_id, ctid) AS rn
    FROM pgb_session.snapshot
    WHERE n IS NULL
)
UPDATE pgb_session.snapshot s
SET n = numbered.rn
FROM numbered
WHERE s.ctid = numbered.ctid;

ALTER TABLE pgb_session.snapshot
    ALTER COLUMN n SET NOT NULL;

-- Add the global identity only when the column does not already have one, so
-- this script remains valid when run in sequence with later migrations. (The
-- per-session conversion in 65_session_per_session_n.sql removes it again.)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'pgb_session.snapshot'::regclass
          AND attname = 'n'
          AND attidentity <> ''
    ) THEN
        ALTER TABLE pgb_session.snapshot
            ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Advance the identity sequence past the largest existing value. COALESCE/`is_called`
-- keep this valid when the table is empty (the sequence cannot be set below 1).
SELECT setval(
    pg_get_serial_sequence('pgb_session.snapshot', 'n'),
    COALESCE(max(n), 1),
    count(*) > 0
)
FROM pgb_session.snapshot;

ALTER TABLE pgb_session.snapshot
    DROP CONSTRAINT IF EXISTS snapshot_pkey;

ALTER TABLE pgb_session.snapshot
    ADD PRIMARY KEY(session_id, n);

\ir 60_pgb_session_open.sql

\ir 60_pgb_session_reload.sql
